### ISSUE TITLE
로그인

### ISSUE THREAD

**Issue by nyj001012** [GunGonGamLee/ft_transcendence#25]
# 로그인
## 플로우
1. 사용자가 로그인 버튼을 클릭한다.
2. 백에서 구글/42 API와 통신하여 로그인한다.
3. 백에서 빈 로그인 페이지로 redirect 한다(Response 참고).
4. 프론트에서 신규 유저임을 확인하여 닉네임 생성 페이지 또는 게임 모드 선택 페이지로 이동한다.

## URL
- 구글 로그인(GET): `/login/google`
- 42 로그인(GET): `/login/42`
 
## Request
- 없음

## Response
- `/login/authorization` 로 리다이렉트
- JWT 토큰
- 빈 화면에 신규 유저임을 나타내는 url_parameter 필요

## 예상되는 에러
- 500 에러: 로그인 API 상의 무응답 등등

**Comment by donghyun1998** [comment]
42 로그인 방식
1. 프론트 -> 42 -> 백 -> -> 프론트
속도와 효율성: 사용자 인증 과정이 직접적이므로 처리 속도가 빠릅니다.
서버 부담 감소: 인증 과정에서 서버의 역할이 줄어들므로 서버 부하가 감소합니다.
직관적인 사용자 경험: 사용자가 인증 과정을 더 명확하게 인지할 수 있습니다.
2. 프론트 -> 백 -> 42 -> 백 -> -> 프론트
보안: 사용자의 인증 정보가 클라이언트와 외부 API 사이에서 직접 전송되지 않으므로, 보안이 강화됩니다.
중앙화된 처리: 인증 로직이 서버에 집중되어 있어 관리가 용이합니다.
토큰 관리: 백엔드에서 API 토큰을 관리하고 저장할 수 있으므로, 클라이언트 측의 보안 취약점을 줄일 수 있습니다.
swagger 작성 용이함
