### ISSUE TITLE
fix: local 게임 버그 발견

### ISSUE THREAD

**Issue by donghyun1998** [GunGonGamLee/ft_transcendence#363]
<img width="1784" alt="스크린샷 2024-02-28 오후 5 46 38" src="https://github.com/GunGonGamLee/ft_transcendence/assets/81581828/e4a0b675-675f-40f5-bd57-31f551819785">

https://github.com/GunGonGamLee/ft_transcendence/assets/81581828/967a086d-4f01-4af2-a257-6148dc6595a8

- 두번째 공 부터 생성 시 비정상적으로 공 속도가 느림
- 게임 중 갑자기 바에 공이 낌
- 잘 하면 위 벽과 아래벽에서 무한으로 튀김

**Comment by nyj001012** [comment]
- `Math.random()` 시 `window.crypto` 이용하여 시드 값 이용
