### ISSUE TITLE
fix: 사파리에서 폰트가 적용되지 않음

### ISSUE THREAD

**Issue by nyj001012** [GunGonGamLee/ft_transcendence#420]
## 개요
사파리 브라우저에서는 폰트가 적용되지 않음

## 참고
- https://devlink.tistory.com/903

**Comment by sejoonkimmm** [comment]
125점을 받기 위해 사파리 호환을 생각했던 거라 수정하지 않아도 될 것 같습니다...!

**Comment by nyj001012** [comment]
> 125점을 받기 위해 사파리 호환을 생각했던 거라 수정하지 않아도 될 것 같습니다...!

알고보니 `register` 페이지에서 폰트 리소스를 불러오지 않아서 생긴 문제라 크롬에서도 해당 이슈가 똑같이 발생할 겁니다. 그래서 사파리 호환을 제쳐두더라도 일단 수정하겠습니다.
