### ISSUE TITLE
[bug] 전적 api 페이지

### ISSUE THREAD

**Issue by LWJ0513** [GunGonGamLee/ft_transcendence#448]
페이지 넘길 때 끝이 어딘질 몰라서 마지막 페이지인 거 알려줬음 좋겠어요

(수정)
- pagination 버튼을 클릭했을 때 page가 1씩 증가하는 것이 아닌, 계속 1로 고정

**Comment by nyj001012** [comment]
마지막 페이지인지는 다음 페이지로 이동하는 페이지네이션 버튼이 불투명해지고 클릭이 안 되도록 해두었습니다.
처음 페이지인 경우도 마찬가지구요. 페이지네이션 버튼 클릭했을 때 페이지 수가 제대로 증가하지 않는 현상이 있어서 해당 부분 수정하겠습니다.
